### ISSUE TITLE
Issue with wildcards on .co.uk domains

### ISSUE THREAD

**Issue by IainKay** [badjware/certbot-dns-cpanel#1]
Hi badjware,

I found an issue with wildcards on .co.uk domains which I fixed in a fork here:
https://github.com/IainKay/certbot-dns-cpanel/commit/1fe8c727d551012da42d16b00e436f57e5108570

**Comment by IainKay** [comment]
I'm not sure if this was an issue with my cPanel server in particular or not, however, I thought I would share with you and if you'd be able to test against another then that would be most appreciated.
If you can replicate the bug, feel free to pull in my change.

**Comment by badjware** [comment]
Hey thank you for bringing this to my attention. Sorry it took me this long to come back to you.

I took a look at your fork and I'd rather avoid putting a special case for .co.uk domains if possible. Other domains such as .co.jp might also be affected.

I do not have a .co.uk domain in my possession to test with. If I work on a generic fix, are you able to test it on your domain? You are of course welcome to propose a pull request if you wish.

Thanks
