### ISSUE TITLE
How to wait longer than 10 seconds for DNS to propagate?

### ISSUE THREAD

**Issue by djmattyg007** [badjware/certbot-dns-cpanel#3]
I regularly experience the newly created DNS record not being available after just 10 seconds. How can I make it wait longer than 10 seconds?

**Comment by badjware** [comment]
Hello, try adding `--certbot-dns-cpanel:cpanel-propagation-seconds 120` to your arguments when you execute certbot. You can also try increase the number of seconds if 120 is not enough.

**Comment by djmattyg007** [comment]
Thanks, that worked! Would you mind if I submitted a PR to add a note about that to the readme?

**Comment by badjware** [comment]
The readme contains a few mistakes so I will add it to it when I fix it in the near future. Thank you for confirming that it worked!
